<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gugler_theme"
 *
 * Auto generated by Extension Builder 2021-08-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
  "title" => "CKEditor 5: language Plugin",
  "description" => "The text part language feature lets you mark the language of text fragments. This way browsers and screen readers can correctly interpret parts written in different languages.",
  "category" => "be",
  "author" => "Markus Ketterer",
  "author_email" => "webdeveloper@gugler.at",
  "state" => "stable",
  "version" => "1.1.0",
  "constraints" => [
    "depends" => [
      'rte_ckeditor' => '12.4.0-13.4.99',
    ],
  ],
];
